# -*- coding: utf-8 -*-
__version__ = "0.1.1"
__author__ = "Ivan Begtin (ivan@begtin.tech)"
__license__ = "BSD"

from .base import PATTERNS_EN, BASE_TIME_PATTERNS, INTEGER_LIKE_PATTERNS
from .bg import PATTERNS_BG
from .cz import PATTERNS_CZ
from .de import PATTERNS_DE
from .es import PATTERNS_ES
from .fr import PATTERNS_FR
from .it import PATTERNS_IT
from .nl import PATTERNS_NL
from .pl import PATTERNS_PL
from .pt import PATTERNS_PT
from .ru import PATTERNS_RU
from .tr import PATTERNS_TR

ALL_PATTERNS = (PATTERNS_EN + INTEGER_LIKE_PATTERNS + PATTERNS_BG +
                PATTERNS_CZ + PATTERNS_DE + PATTERNS_ES + PATTERNS_FR +
                PATTERNS_IT + PATTERNS_NL + PATTERNS_PL + PATTERNS_PT +
                PATTERNS_RU + PATTERNS_TR)


# Authoritative per-pattern metadata: basekey -> (language, separator).
#
# This is the single source of truth for a pattern's language and separator. It
# replaces the three copies of substring-based inference that previously lived in
# qdparser.py (_infer_char_sets, _build_language_index, _build_separator_index) and
# the ~15 hand-synced basekey lists in dirty.py. Adding a language or pattern means
# adding one entry here, not editing multiple inference sites.
#
# `language` is None for language-neutral numeric patterns (e.g. date_1, date_iso8601)
# that any language can consume. `separator` is one of slash/dot/dash/space/none/mixed.
#
# Verified behavior-preserving: each entry was generated by running the exact
# pre-refactor substring inference against the same pattern set, so this table
# reproduces today's candidate filtering bit-for-bit. See design notes in
# openspec/changes/refactor-pattern-metadata/design.md.
_PATTERN_METADATA = {
    # Numeric / language-neutral patterns (base.py + INTEGER_LIKE_PATTERNS)
    'dt:date:date_1': (None, 'slash'),
    'dt:date:date_2': (None, 'dot'),
    'dt:date:date_3': (None, 'slash'),
    'dt:date:date_4': (None, 'dot'),
    'dt:date:date_iso8601': (None, 'dash'),
    'dt:date:date_iso8601_short': (None, 'dash'),
    'dt:date:date_8': (None, 'slash'),
    'dt:date:date_9': (None, 'dash'),
    'dt:date:date_10': (None, 'dot'),
    'dt:date:noyear_1': (None, 'dot'),
    'dt:date:date_4_point': (None, 'dot'),
    'dt:date:date_5': (None, 'none'),
    'dt:date:date_6': (None, 'none'),
    # English (base.py) — numeric and month-name patterns
    'dt:date:date_usa_1': ('en', 'slash'),
    'dt:date:date_usa': ('en', 'slash'),
    'dt:date:date_eng1': ('en', 'dot'),
    'dt:date:date_eng1x': ('en', 'dot'),
    'dt:date:date_eng1_lc': ('en', 'dot'),
    'dt:date:date_eng1_short': ('en', 'dot'),
    'dt:date:date_eng2': ('en', 'space'),
    'dt:date:date_eng2_lc': ('en', 'space'),
    'dt:date:date_eng2_short': ('en', 'space'),
    'dt:date:date_eng3': ('en', 'space'),
    'dt:date:date_eng3_nolc': ('en', 'space'),
    'dt:date:date_eng4_short': ('en', 'space'),
    'dt:date:weekday_eng': ('en', 'space'),
    'dt:date:weekday_eng_lc': ('en', 'space'),
    'dt:date:weekday_eng_wshort': ('en', 'space'),
    'dt:date:weekday_eng_mshort_wshort': ('en', 'space'),
    'dt:date:weekday_eng_iso': ('en', 'space'),
    'dt:date:weekday_short_eng_iso': ('en', 'space'),
    'dt:date:weekday_eng_mixed': ('en', 'space'),
    'dt:date:date_eng_abbrev1': ('en', 'space'),
    'dt:date:date_eng_abbrev2': ('en', 'space'),
    'dt:date:date_eng_abbrev3': ('en', 'space'),
    'dt:date:weekday_eng_abbrev1': ('en', 'space'),
    'dt:date:weekday_eng_abbrev2': ('en', 'space'),
    'dt:date:weekday_eng_abbrev3': ('en', 'space'),
    'dt:date:date_eng_abbrev_postfix': ('en', 'space'),
    # Bulgarian (bg.py)
    'dt:date:bg_base': ('bg', 'space'),
    'dt:date:bg_base_lc': ('bg', 'space'),
    # Czech (cz.py)
    'dt:date:cz_base': ('cz', 'space'),
    'dt:date:cz_base_lc': ('cz', 'space'),
    'dt:date:cz_gen': ('cz', 'space'),
    'dt:date:cz_gen_lc': ('cz', 'space'),
    # German (de.py)
    'dt:date:de_base': ('de', 'space'),
    'dt:date:de_base_lc': ('de', 'space'),
    'dt:date:de_weekday': ('de', 'space'),
    'dt:date:de_weekday_lc': ('de', 'space'),
    'dt:date:de_short': ('de', 'space'),
    'dt:date:de_short_lc': ('de', 'space'),
    'dt:date:de_rare_1': ('de', 'slash'),
    'dt:date:de_rare_2': ('de', 'dot'),
    # Spanish (es.py)
    'dt:date:es_base': ('es', 'space'),
    'dt:date:es_base_lc': ('es', 'space'),
    'dt:date:es_base_article': ('es', 'space'),
    'dt:date:es_base_lc_article': ('es', 'space'),
    'dt:date:es_rare_1': ('es', 'slash'),
    'dt:date:es_rare_2': ('es', 'dot'),
    'dt:date:es_short': ('es', 'space'),
    'dt:date:es_short_lc': ('es', 'space'),
    'dt:date:es_short_monthfirst': ('es', 'space'),
    'dt:date:es_short_lc_monthfirst': ('es', 'space'),
    'dt:date:es_weekday': ('es', 'space'),
    'dt:date:es_weekday_lc': ('es', 'space'),
    # French (fr.py)
    'dt:date:fr_base': ('fr', 'space'),
    'dt:date:fr_base_lc': ('fr', 'space'),
    'dt:date:fr_base_article': ('fr', 'space'),
    'dt:date:fr_base_lc_article': ('fr', 'space'),
    'dt:date:fr_short': ('fr', 'space'),
    'dt:date:fr_short_lc': ('fr', 'space'),
    'dt:date:fr_short_monthfirst': ('fr', 'space'),
    'dt:date:fr_short_lc_monthfirst': ('fr', 'space'),
    'dt:date:fr_weekday': ('fr', 'space'),
    'dt:date:fr_weekday_lc': ('fr', 'space'),
    # Italian (it.py)
    'dt:date:it_base': ('it', 'space'),
    'dt:date:it_base_lc': ('it', 'space'),
    'dt:date:it_base_article': ('it', 'space'),
    'dt:date:it_base_lc_article': ('it', 'space'),
    'dt:date:it_rare_1': ('it', 'slash'),
    'dt:date:it_rare_2': ('it', 'dot'),
    'dt:date:it_weekday': ('it', 'space'),
    'dt:date:it_weekday_lc': ('it', 'space'),
    'dt:date:it_short': ('it', 'space'),
    'dt:date:it_short_lc': ('it', 'space'),
    'dt:date:it_short_monthfirst': ('it', 'space'),
    'dt:date:it_short_lc_monthfirst': ('it', 'space'),
    # Dutch (nl.py)
    'dt:date:nl_base': ('nl', 'space'),
    'dt:date:nl_base_lc': ('nl', 'space'),
    'dt:date:nl_weekday': ('nl', 'space'),
    'dt:date:nl_weekday_lc': ('nl', 'space'),
    'dt:date:nl_short': ('nl', 'space'),
    'dt:date:nl_short_lc': ('nl', 'space'),
    'dt:date:nl_rare_1': ('nl', 'slash'),
    'dt:date:nl_rare_2': ('nl', 'dot'),
    # Polish (pl.py)
    'dt:date:pl_base': ('pl', 'space'),
    'dt:date:pl_base_lc': ('pl', 'space'),
    'dt:date:pl_gen': ('pl', 'space'),
    'dt:date:pl_gen_lc': ('pl', 'space'),
    # Portuguese (pt.py)
    'dt:date:pt_base': ('pt', 'space'),
    'dt:date:pt_base_lc': ('pt', 'space'),
    'dt:date:pt_base_article': ('pt', 'space'),
    'dt:date:pt_base_lc_article': ('pt', 'space'),
    'dt:date:pt_short': ('pt', 'space'),
    'dt:date:pt_short_lc': ('pt', 'space'),
    'dt:date:pt_short_monthfirst': ('pt', 'space'),
    'dt:date:pt_short_lc_monthfirst': ('pt', 'space'),
    'dt:date:pt_weekday': ('pt', 'space'),
    'dt:date:pt_weekday_lc': ('pt', 'space'),
    'dt:date:pt_weekday_short': ('pt', 'space'),
    'dt:date:pt_weekday_short_lc': ('pt', 'space'),
    # Russian (ru.py)
    'dt:date:date_rus': ('ru', 'space'),
    'dt:date:date_rus2': ('ru', 'space'),
    'dt:date:date_rus3': ('ru', 'dot'),
    'dt:date:date_rus_lc1': ('ru', 'space'),
    'dt:date:date_rus_lc2': ('ru', 'space'),
    'dt:date:weekday_rus': ('ru', 'space'),
    'dt:date:weekday_rus_lc1': ('ru', 'space'),
    'dt:date:rus_rare_2': ('ru', 'dot'),
    'dt:date:rus_rare_3': ('ru', 'dot'),
    'dt:date:rus_rare_5': ('ru', 'space'),
    'dt:date:rus_rare_6': ('ru', 'space'),
    # Turkish (tr.py)
    'dt:date:tr_base': ('tr', 'space'),
    'dt:date:tr_base_lc': ('tr', 'space'),
}


def annotate_patterns(patterns):
    """Stamp explicit ``language`` and ``separator`` fields onto each pattern.

    Idempotent: skips patterns that already carry both fields. Falls back to the
    ``mixed`` separator and ``None`` language when a key is not in the metadata
    table, so a missing entry degrades gracefully rather than crashing (the
    coverage test flags any such gap).

    :param patterns: iterable of pattern dicts (mutated in place)
    :return: the same list (for chaining)
    """
    for pat in patterns:
        if "language" in pat and "separator" in pat:
            continue
        lang, sep = _PATTERN_METADATA.get(pat["key"], (None, "mixed"))
        pat.setdefault("language", lang)
        pat.setdefault("separator", sep)
    return patterns


# Numeric-only patterns: they require only digit characters to match, even when
# they carry a language tag. ``date_usa`` / ``date_usa_1`` are US-locale
# (language="en") but their *format* is purely numeric (mm/dd/yyyy), so they must
# not require Latin characters. This set drives the digit-only charset branch.
_NUMERIC_PATTERN_KEYS = frozenset({
    "dt:date:date_1", "dt:date:date_2", "dt:date:date_3", "dt:date:date_4",
    "dt:date:date_iso8601", "dt:date:date_iso8601_short", "dt:date:date_8",
    "dt:date:date_9", "dt:date:date_10", "dt:date:noyear_1",
    "dt:date:date_4_point", "dt:date:date_5", "dt:date:date_6",
    "dt:date:date_usa_1", "dt:date:date_usa",
})


# Stamp metadata onto the canonical pattern list once at import, so every consumer
# (DateParser, dirty.py, tests) reads the same authoritative fields.
annotate_patterns(ALL_PATTERNS)

SUPPORTED_LANGUAGES = [
    "bg",
    "cz",
    "de",
    "en",
    "es",
    "fr",
    "it",
    "nl",
    "pl",
    "pt",
    "ru",
    "tr",
]

# Mapping of language codes to their pattern lists
PATTERNS_BY_LANGUAGE = {
    "en": PATTERNS_EN + INTEGER_LIKE_PATTERNS,
    "bg": PATTERNS_BG,
    "cz": PATTERNS_CZ,
    "de": PATTERNS_DE,
    "es": PATTERNS_ES,
    "fr": PATTERNS_FR,
    "it": PATTERNS_IT,
    "nl": PATTERNS_NL,
    "pl": PATTERNS_PL,
    "pt": PATTERNS_PT,
    "ru": PATTERNS_RU,
    "tr": PATTERNS_TR,
}


def get_patterns_for_languages(languages):
    """Get patterns for specified languages.
    
    :param languages: Language code (str) or list of language codes (list of str).
                     If None or empty, returns all patterns.
    :type languages: str|list|None
    :return: Combined list of patterns for specified languages
    :rtype: list
    :raises ValueError: If any language code is not in SUPPORTED_LANGUAGES
    """
    if languages is None:
        return ALL_PATTERNS
    
    # Normalize to list
    if isinstance(languages, str):
        languages = [languages]
    elif not isinstance(languages, (list, tuple)):
        raise TypeError("languages must be a string, list of strings, or None")
    
    if len(languages) == 0:
        return ALL_PATTERNS
    
    # Validate all language codes
    invalid_languages = [lang for lang in languages if lang not in SUPPORTED_LANGUAGES]
    if invalid_languages:
        raise ValueError(
            f"Unsupported language(s): {invalid_languages}. "
            f"Supported languages: {SUPPORTED_LANGUAGES}"
        )
    
    # Combine patterns for specified languages
    patterns = []
    for lang in languages:
        patterns.extend(PATTERNS_BY_LANGUAGE[lang])
    
    return patterns